blank_issues_enabled: false
contact_links:
  - name: Ask Java Community
    url: https://github.com/HamzasZaitoun/learning-roadmap/discussions
    about: Ask questions and share insights related to Java, Spring Boot, or your journey.
